# Generated by Django 4.2.6 on 2023-11-07 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_work_date', models.DateField(blank=True, null=True)),
                ('is_half', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('Contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaveRequestemployee', to='contract.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaveRequestcreatedby', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaveRequestdeletedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1-Data-Leave-LeaveRequest',
            },
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RequestLeaveAprove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Review', 'Review'), ('Acepted', 'Acepted'), ('Rejected', 'Rejected')], max_length=30, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestLeaveAprovecreatedby', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestLeaveAprovedeletedby', to=settings.AUTH_USER_MODEL)),
                ('employeeuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestLeaveAproveuser', to='employee.employeeuser')),
                ('leaverequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestLeaveAproveleaverequest', to='leave.leaverequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestLeaveAproveupdatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1-Data-Purchase_Request-Request_Order_Aprove',
            },
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('total', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaveTypecreatedbys', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaveTypedeletedbys', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaveTypeupdatetedbys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '01-Data-Leave-LeaveType',
            },
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leavetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaveRequestleavetype', to='leave.leavetype'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaveRequestupdatedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
