# Generated by Django 4.2.6 on 2023-11-09 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_initial'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='Contract',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaveRequestcontract', to='contract.contract'),
        ),
    ]
