# Generated by Django 4.2.6 on 2023-11-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_remove_leaverequest_contract_leaverequest_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_historical',
            field=models.BooleanField(default=False),
        ),
    ]
