# Generated by Django 4.2.6 on 2023-11-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaverequest_is_historical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_half',
        ),
    ]
