# Generated by Django 4.2.6 on 2023-11-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_rename_is_historical_leaverequest_is_aproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_aproved',
        ),
    ]
